# Generated by Django 4.0.1 on 2022-04-07 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_product_name_af_remove_product_name_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=50, verbose_name='Mavzusi')),
                ('title', models.CharField(max_length=150, verbose_name='Nomi')),
                ('bg_image', models.ImageField(upload_to=None, verbose_name='Rasmi')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-id',), 'verbose_name': 'KATEGORIYALAR', 'verbose_name_plural': 'KATEGORIYALAR'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created',), 'verbose_name': 'MAXSULOTLAR', 'verbose_name_plural': 'MAXSULOTLAR'},
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set(),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_products', to='main.category', verbose_name='Kategoriyasi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name="Ta'rifi"),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product_images/', verbose_name='Rasmi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Avvalgi narxi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=250, verbose_name='*'),
        ),
    ]
