# Generated by Django 4.0.1 on 2022-04-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_name_ru_category_name_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.IntegerField(verbose_name='Telefon')),
                ('address', models.CharField(max_length=50, verbose_name='Manzil')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'SLIDERS', 'verbose_name_plural': 'SLIDERS'},
        ),
        migrations.AlterField(
            model_name='slider',
            name='bg_image',
            field=models.ImageField(upload_to='slide_image', verbose_name='Rasmi'),
        ),
    ]
