# Generated by Django 4.0.1 on 2022-04-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_myuser_email_remove_myuser_last_login_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ('-id',), 'verbose_name': 'FOYDALANUVCHILAR', 'verbose_name_plural': 'FOYDALANUVCHILAR'},
        ),
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.CharField(max_length=50, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='Telefon'),
        ),
    ]
